#pragma once
/**
 * @file hub_ref_config.hpp
 * @brief HubRefConfig — role-side reference to a hub directory.
 *
 * Parsed from directional JSON fields `<direction>_hub_dir` in role configs;
 * resolves the broker endpoint and CURVE pubkey from the named hub directory's
 * `hub.json` and `hub.pubkey`.  This is the role's *reference* to a hub —
 * not the hub's own configuration.
 *
 * The hub-side composite config lives at `hub_config.hpp` (HEP-CORE-0033 §6.1)
 * and uses the `HubConfig` symbol; this file was renamed from
 * `hub_config.hpp` → `hub_ref_config.hpp` (and class `HubConfig` →
 * `HubRefConfig`) in HEP-0033 Phase 1 (G10) to free that name.
 */

#include "utils/json_fwd.hpp"

#include <filesystem>
#include <fstream>
#include <string>

namespace pylabhub::config
{

struct HubRefConfig
{
    std::string hub_dir;        ///< Resolved absolute path to hub directory (or empty).
    std::string broker;         ///< Broker endpoint, e.g. "tcp://127.0.0.1:5570".
    std::string broker_pubkey;  ///< Z85 CURVE25519 public key (40 chars, or empty).
};

/// Parse a role-side hub reference for a given direction ("in" or "out").
/// Reads <direction>_hub_dir from JSON, resolves broker endpoint + pubkey
/// from the hub directory if present.
/// @param j         Root JSON object.
/// @param base_dir  Role directory base (for resolving relative hub_dir).
/// @param direction "in" or "out".
inline HubRefConfig parse_hub_ref_config(const nlohmann::json &j,
                                         const std::filesystem::path &base_dir,
                                         const char *direction)
{
    namespace fs = std::filesystem;
    const std::string prefix = std::string(direction) + "_";

    HubRefConfig hc;
    const std::string hub_dir_raw = j.value(prefix + "hub_dir", std::string{});

    if (hub_dir_raw.empty())
        return hc;

    // Resolve relative to role base directory.
    const fs::path p(hub_dir_raw);
    const fs::path resolved = p.is_absolute()
                              ? fs::weakly_canonical(p)
                              : fs::weakly_canonical(base_dir / p);
    hc.hub_dir = resolved.string();

    // Read broker endpoint from hub.json.  HEP-0033 §6.2 places
    // `broker_endpoint` under the top-level `network` block; the
    // legacy demo hub.json files (`share/py-demo-*/hub/hub.json`)
    // still use `hub.broker_endpoint`.  Try the new path first, fall
    // back to the legacy path so role configs work against either
    // shape during the HEP-0033 transition.  (Once the demos are
    // regenerated by `plh_hub --init` in Phase 9, the legacy fallback
    // can be removed.)
    const auto hub_json_path = resolved / "hub.json";
    std::ifstream hf(hub_json_path);
    if (hf.is_open())
    {
        try
        {
            const auto hj = nlohmann::json::parse(hf);
            if (hj.contains("network") && hj["network"].is_object() &&
                hj["network"].contains("broker_endpoint"))
                hc.broker = hj["network"]["broker_endpoint"].get<std::string>();
            else if (hj.contains("hub") && hj["hub"].is_object() &&
                     hj["hub"].contains("broker_endpoint"))
                hc.broker = hj["hub"]["broker_endpoint"].get<std::string>();
        }
        catch (const std::exception &)
        {
            // hub.json exists but malformed — leave broker empty,
            // caller decides.
        }
    }

    // Read broker pubkey from hub.pubkey.
    const auto pubkey_path = resolved / "hub.pubkey";
    if (fs::exists(pubkey_path))
    {
        std::ifstream pk(pubkey_path);
        std::getline(pk, hc.broker_pubkey);
    }

    return hc;
}

} // namespace pylabhub::config
