"""Type stubs for the `pylabhub_hub` embedded pybind11 module.

Hand-authored — keep in sync with `src/scripting/hub_api_python.cpp`
PYBIND11_EMBEDDED_MODULE block.  Surfaces the hub-side script API
(HEP-CORE-0033 §12.3).
"""

from typing import Any, List, Optional

__all__ = ["HubAPI"]


class HubAPI:
    """Hub-side script API surface (HEP-CORE-0033 §12.3).

    Exposed as a module global `api` to scripts after
    PythonEngine::build_api_(HubAPI&) wires it.
    """

    # ── Lifecycle / log / uid / metrics ─────────────────────────────
    def log(self, level: str, msg: str) -> None: ...
    def uid(self) -> str: ...
    def metrics(self) -> dict: ...

    # ── Read accessors (HEP-CORE-0033 §12.3 read block) ─────────────
    def name(self) -> str: ...
    def config(self) -> dict: ...
    def list_channels(self) -> list: ...
    def get_channel(self, name: str) -> Optional[dict]: ...
    def list_roles(self) -> list: ...
    def get_role(self, role_uid: str) -> Optional[dict]: ...
    def list_bands(self) -> list: ...
    def get_band(self, name: str) -> Optional[dict]: ...
    def list_peers(self) -> list: ...
    def get_peer(self, hub_uid: str) -> Optional[dict]: ...
    def query_metrics(self, categories: List[str] = ...) -> dict: ...

    # ── Control delegates ───────────────────────────────────────────
    def close_channel(self, name: str) -> None: ...
    def broadcast_channel(self, channel: str, message: str, data: str = ...) -> None: ...
    def request_shutdown(self) -> None: ...

    # ── Augmentation timeout (HEP-CORE-0033 §12.2.2) ───────────────
    def augment_timeout_ms(self) -> int: ...
    def set_augment_timeout(self, ms: int) -> None: ...

    # ── User events (HEP-CORE-0033 §12.2.3) ────────────────────────
    def post_event(self, name: str, data: Any = ...) -> None:
        """Post a user-defined event onto the worker's main-loop queue.

        Raises ValueError if `name` is not a valid C identifier.
        Fires `on_app_<name>(api, data)` on the worker thread.
        """
        ...
