"""Type stubs for the `pylabhub_producer` embedded pybind11 module.

Stable for the v6 ABI baseline + v7 hub-side surface
(HEP-CORE-0028 §4.1).  Hand-authored — keep in sync with
`src/producer/producer_api.cpp` PYBIND11_EMBEDDED_MODULE block.
"""

from typing import Any, Optional

__all__ = [
    "ProducerAPI",
    "TxChannel",
    "RxChannel",
    "InboxMsg",
    "SpinLock",
    "InboxHandle",
    "StopReason",
    "version_info",
]


def version_info() -> str:
    """Return the version-registry JSON for this build."""
    ...


class TxChannel:
    slot: Any


class RxChannel:
    slot: Any


class InboxMsg:
    data: bytes
    sender_uid: str
    seq: int


class StopReason:
    """String constants matching values returned by `api.stop_reason()`."""
    Normal: str
    PeerDead: str
    HubDead: str
    CriticalError: str
    ChannelClosed: str
    ScriptError: str


class SpinLock:
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def try_lock_for(self, timeout_ms: int) -> bool: ...
    def is_locked_by_current_process(self) -> bool: ...
    def __enter__(self) -> "SpinLock": ...
    def __exit__(self, exc_type: Any, exc_value: Any, tb: Any) -> None: ...


class InboxHandle:
    def acquire(self) -> Any: ...
    def send(self, timeout_ms: int = 5000) -> bool: ...
    def discard(self) -> None: ...
    def is_ready(self) -> bool: ...
    def close(self) -> None: ...


class ProducerAPI:
    """Producer-side scripting surface.

    Bound by `PythonEngine::build_api_(RoleAPIBase&)` and exposed to
    scripts as the module-global `api`.
    """

    Tx: int
    Rx: int

    shared_data: dict
    """Shared script data dictionary. Persists across callbacks."""

    # ── Identity ────────────────────────────────────────────────────
    def uid(self) -> str: ...
    def name(self) -> str: ...
    def channel(self) -> str: ...
    def log_level(self) -> str: ...
    def script_dir(self) -> str: ...
    def role_dir(self) -> str: ...
    def logs_dir(self) -> str: ...
    def run_dir(self) -> str: ...

    # ── Lifecycle ───────────────────────────────────────────────────
    def stop(self) -> None: ...
    def set_critical_error(self, msg: str) -> None: ...
    def critical_error(self) -> bool: ...
    def stop_reason(self) -> str:
        """Why the role stopped: 'normal', 'peer_dead', 'hub_dead',
        'critical_error', 'channel_closed', or 'script_error'.

        Compare against `pylabhub_producer.StopReason.*` constants
        for linter-friendly checks.
        """
        ...
    def log(self, level: str, msg: str) -> None: ...

    # ── Flexzone ────────────────────────────────────────────────────
    def flexzone(self, side: Optional[int] = ...) -> Any: ...
    def update_flexzone_checksum(self) -> bool: ...

    # ── Band pub/sub (HEP-CORE-0030) ───────────────────────────────
    def band_join(self, channel: str) -> Optional[dict]: ...
    def band_leave(self, channel: str) -> bool: ...
    def band_broadcast(self, channel: str, body: dict) -> None: ...
    def band_members(self, channel: str) -> Optional[list]: ...
    def band_member_contains(self, channel: str, role_uid: str) -> bool: ...
    def band_member_count(self, channel: str) -> int: ...
    def is_in_band(self, channel: str) -> bool: ...

    # ── Diagnostics ─────────────────────────────────────────────────
    def script_error_count(self) -> int: ...
    def out_slots_written(self) -> int: ...
    def out_drop_count(self) -> int: ...
    def loop_overrun_count(self) -> int: ...
    def out_capacity(self) -> int: ...
    def out_policy(self) -> str: ...
    def last_cycle_work_us(self) -> int: ...
    def metrics(self) -> dict: ...

    # ── Channel auth (HEP-CORE-0036 §I11 / §6.7) ────────────────────
    def allowed_peers(self, channel: str) -> list: ...
    def allowed_peer_contains(self, channel: str, role_uid: str) -> bool: ...
    def allowed_peer_count(self, channel: str) -> int: ...
    def is_channel_ready(self, channel: str) -> bool: ...
    def queue_mechanism(self, side: int) -> str: ...

    # ── Schema sizes ────────────────────────────────────────────────
    def slot_logical_size(self, side: Optional[int] = ...) -> int: ...
    def flexzone_logical_size(self, side: Optional[int] = ...) -> int: ...

    # ── Spinlocks (HEP-CORE-0002) ───────────────────────────────────
    def spinlock(self, index: int, side: Optional[int] = ...) -> SpinLock: ...
    def spinlock_count(self, side: Optional[int] = ...) -> int: ...

    # ── Custom metrics ──────────────────────────────────────────────
    def report_metric(self, key: str, value: float) -> None: ...
    def report_metrics(self, kv: dict) -> None: ...
    def clear_custom_metrics(self) -> None: ...

    # ── Inbox ───────────────────────────────────────────────────────
    def open_inbox(self, target_uid: str) -> Optional[InboxHandle]: ...
    def clear_inbox_cache(self) -> None: ...
    def wait_for_role(self, uid: str, timeout_ms: int = 5000) -> bool: ...

    @staticmethod
    def as_numpy(ctypes_array: Any) -> Any:
        """Convert a ctypes array field to a numpy ndarray view (zero-copy)."""
        ...
