/**
 * @file test_hub_config.cpp
 * @brief Pattern 3 driver: HubConfig L2 unit-test suite (HEP-CORE-0033 §6.1).
 *
 * Verifies the hub-side composite config: pImpl + JsonConfig backend,
 * strict-key whitelist parsing, sub-config delegation, vault hooks,
 * `reload_if_changed`.  Each TEST_F spawns one worker process that owns
 * its own LifecycleGuard (Logger + FileLock + JsonConfig).
 */
#include "test_patterns.h"

#include <gtest/gtest.h>

#include <atomic>
#include <filesystem>
#include <string>
#include <unistd.h>

namespace fs = std::filesystem;
using pylabhub::tests::IsolatedProcessTest;

namespace
{

class HubConfigTest : public IsolatedProcessTest
{
  protected:
    void TearDown() override
    {
        for (const auto &p : paths_to_clean_)
        {
            std::error_code ec;
            fs::remove_all(p, ec);
        }
        paths_to_clean_.clear();
    }

    std::string unique_dir(const char *test_name)
    {
        static std::atomic<int> ctr{0};
        fs::path p = fs::temp_directory_path() /
                     ("plh_l2_hcfg_" + std::string(test_name) + "_" +
                      std::to_string(::getpid()) + "_" +
                      std::to_string(ctr.fetch_add(1)));
        fs::create_directories(p);
        paths_to_clean_.push_back(p);
        return p.string();
    }

    std::vector<fs::path> paths_to_clean_;
};

} // namespace

TEST_F(HubConfigTest, LoadFull_AllSectionsParsed)
{
    auto w = SpawnWorker("hub_config.load_full",
                         {unique_dir("load_full")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, LoadMinimal_DefaultsApplied)
{
    auto w = SpawnWorker("hub_config.load_minimal",
                         {unique_dir("load_minimal")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, StrictKeys_UnknownTopLevel_Throws)
{
    auto w = SpawnWorker("hub_config.strict_unknown_top_level",
                         {unique_dir("strict_unknown_top_level")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, StrictKeys_UnknownInSection_Throws)
{
    auto w = SpawnWorker("hub_config.strict_unknown_in_section",
                         {unique_dir("strict_unknown_in_section")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, SectionNotObject_Throws)
{
    auto w = SpawnWorker("hub_config.section_not_object",
                         {unique_dir("section_not_object")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, Uid_AutoGenerated_When_Absent)
{
    auto w = SpawnWorker("hub_config.uid_auto_generated",
                         {unique_dir("uid_auto_generated")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, State_GraceSentinel_NegativeOne_BecomesInfinite)
{
    auto w = SpawnWorker("hub_config.state_grace_sentinel",
                         {unique_dir("state_grace_sentinel")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, LoadFromDirectory_EquivalentToExplicitPath)
{
    auto w = SpawnWorker("hub_config.load_from_directory",
                         {unique_dir("load_from_directory")});
    ExpectWorkerOk(w);
}

TEST_F(HubConfigTest, ReloadIfChanged_NoChangeFalse_AfterModifyTrue)
{
    auto w = SpawnWorker("hub_config.reload_if_changed",
                         {unique_dir("reload_if_changed")});
    ExpectWorkerOk(w);
}

// Cross-cutting: HubDirectory::init_directory must write a template that
// HubConfig::load_from_directory accepts without throwing.  Catches drift
// between the template (hub_directory.cpp::build_hub_json_template) and
// the parser whitelist (hub_config.cpp::kAllowedTopLevelKeys + each
// sub-section parser).
TEST_F(HubConfigTest, InitTemplate_LoadsViaHubConfig)
{
    auto w = SpawnWorker("hub_config.init_template_loads_via_hubconfig",
                         {unique_dir("init_template_round_trip")});
    ExpectWorkerOk(w);
}
