name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      # Install your package (so imports work) + test deps
      - run: pip install -e .
      - run: pip install -r requirements.txt pytest
      # Run tests (explicit path is fine too: pytest -q tests)
      - run: pytest -q
