name: Publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"   # publish when you push a version tag like v0.0.1
permissions:
  id-token: write  # IMPORTANT for OIDC
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip build
      - run: python -m build  # builds sdist + wheel in ./dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No token needed; uses OIDC (Trusted Publishing)
          # repository-url: https://test.pypi.org/legacy/  # uncomment if testing on TestPyPI
          print-hash: true
